### ISSUE TITLE
`accProcess` fails when parsing files in the current directory

### ISSUE THREAD

**Issue by angerhang** [OxWearables/biobankAccelerometerAnalysis#197]
```
(home_Env) hangy@NDPH8334 data % accProcess sample_v2.gt3x 
Traceback (most recent call last):
  File "/Users/hangy/opt/miniconda3/envs/home_Env/bin/accProcess", line 8, in <module>
    sys.exit(main())
  File "/Users/hangy/opt/miniconda3/envs/home_Env/lib/python3.9/site-packages/accelerometer/accProcess.py", line 297, in main
    assert os.access(path, os.W_OK), (
AssertionError: Either folder '' does not exist or you do not have write permission
```

**Comment by chanshing** [comment]
@angerhang @R-Walmsley Anyone interested in fixing this?

**Comment by chanshing** [comment]
Couldn't reproduce.
