### ISSUE TITLE
GT3X broken during calibration

### ISSUE THREAD

**Issue by angerhang** [OxWearables/biobankAccelerometerAnalysis#202]
When processing certain GT3X, current accProcess breaks. Not sure why this is the case.

```bash
2022-06-21 17:11:09	=== Calibrating ===
unknown parameter csvSampleRate:30.0
Device's initial offset: 08:00:00
Start date (local UNIX): -1
Stop date (local UNIX): -62135596800000
sampleFreq:30.0
sampleDelta before rounding:33.33
sampleDelta after rounding:33.333333333333336
Interrupt of length: 2065.033s, at epoch 2016-06-22T11:00:50.033+08:00[Australia/Perth] 
 from: 2016-06-22T11:00:59+08:00[Australia/Perth]
 to  : 2016-06-22T11:35:24.033+08:00[Australia/Perth]
Traceback (most recent call last):
  File "/well/doherty/users/cxx579/conda/envs/raine_parsing/bin/accProcess", line 8, in <module>
    sys.exit(main())
  File "/well/doherty/users/cxx579/conda/envs/raine_parsing/lib/python3.8/site-packages/accelerometer/accProcess.py", line 305, in main
    accelerometer.device.processInputFileToEpoch(
  File "/well/doherty/users/cxx579/conda/envs/raine_parsing/lib/python3.8/site-packages/accelerometer/device.py", line 126, in processInputFileToEpoch
    getCalibrationCoefs(stationaryFile, summary)
  File "/well/doherty/users/cxx579/conda/envs/raine_parsing/lib/python3.8/site-packages/accelerometer/device.py", line 297, in getCalibrationCoefs
    slopeT[k] = params[2] + (slopeT[k] * params[1])
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by angerhang** [comment]
I am not sure what t stands for here, maybe time? But when I am replicating the same linear regression with a toy example,
it only returns two coefficients too instead of 3.


![Screenshot 2022-06-21 at 17 35 33](https://user-images.githubusercontent.com/7655454/174852151-01c8bf74-2fd2-4175-95e5-ee5d5b65e4e7.png)

**Comment by chanshing** [comment]
Hey Hang, thanks for finding this issue.
Turns out `sm.add_constant` tries to be smart by not including the bias term when there's already a column of 1s, which was the case with that specific file (temperature was 1 all across for some reason).
Will fix soon.
