### ISSUE TITLE
csv input file 

### ISSUE THREAD

**Issue by RachelOwl** [OxWearables/biobankAccelerometerAnalysis#58]
what should be the format of an input file here?
 I have csv file with x y z time I ran the file
python accProcess.py data/input_file.csv  --sampleRate 25 --csvTimeFormat "yyyy-MM-dd HH:mm:ss.SSS" --csvXYZTCols 0,1,2,3 but kee getting:
Interrupt of length: 133.08s, at epoch 2020-05-09T20:58:11.930+01:00[Europe/London] 
from: 2020-05-09T20:58:28.345+01:00[Europe/London]
 to  : 2020-05-09T21:00:41.425+01:00[Europe/London]

in the summarizing part I get the error:
2020-07-01 15:11:45     === Summarizing ===
Traceback (most recent call last):
  File "accProcess.py", line 423, in <module>
    main()  # Standard boilerplate to call the main() function to begin the program.
  File "accProcess.py", line 359, in main
    verbose=args.verbose)
  File "/Users/rachelshalom/Desktop/ML/biobankAccelerometerAnalysis/accelerometer/summariseEpoch.py", line 108, in getActivitySummary
    e = get_interrupts(e, epochPeriod, summary)
  File "/Users/rachelshalom/Desktop/ML/biobankAccelerometerAnalysis/accelerometer/summariseEpoch.py", line 173, in get_interrupts
    summary['errs-interrupt-mins'] = accUtils.formatNum(np.sum(interruptMins), 1)
  File "/Users/rachelshalom/Desktop/ML/biobankAccelerometerAnalysis/accelerometer/accUtils.py", line 35, in formatNum
    return float(fmt % num)
  File "/Users/rachelshalom/opt/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 112, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>

**Comment by muschellij2** [comment]
Was this ever resolved?

**Comment by chanshing** [comment]
@muschellij2 It should be. Are you facing issues processing a CSV file?
